### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by vreuter**
`master` into `dev` conflict resolution

### CODE REVIEW

**Comment by nsheff** [comment]
No matching distribution found for ubiquerg>=0.4.4

**Comment by vreuter** [comment]
> No matching distribution found for ubiquerg>=0.4.4

Yeah why's that in here? It doesn't exist.

**Comment by vreuter** [comment]
> > No matching distribution found for ubiquerg>=0.4.4
> 
> Yeah why's that in here? It doesn't exist.

OK, exists now; let's see what Travis has to say

**Comment by nsheff** [comment]
probably I put it in because it needed 'is_command_callable', which wasn't released yet, so this was depending on the next ubiquerg, which I assumed would be released first, but wasn't. my bad.

**Pull request merged**
